version: "3.9"

networks:
  postgres_network:
    driver: bridge

volumes:
  replica_data:

services:

  replica:
    container_name: replica_container
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - PGUSER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - replica_data:/var/lib/postgresql/data
    command: >
      sh -c '
      echo "Waiting for primary database to be ready...";
      until pg_isready -h primary -p 5432; do sleep 2; done;

      echo "Waiting additional time for replica user to be created...";
      sleep 10;

      echo "Force initializing replica from primary...";
      rm -rf /var/lib/postgresql/data/*;
      gosu postgres pg_basebackup -h primary -D /var/lib/postgresql/data -U replica_user -X stream -c fast -P -R;
      echo "Fixing permissions on data directory...";
      chown -R postgres:postgres /var/lib/postgresql/data;
      chmod -R 0700 /var/lib/postgresql/data;

      echo "Starting replica...";
      gosu postgres postgres -c max_connections=500'
    ports:
      - "5433:5432"
    networks:
      - postgres_network
    depends_on:
      primary:
        condition: service_healthy
    restart: unless-stopped