version: "3.9"

networks:
  postgres_network:
    driver: bridge

volumes:
  migration_data:

services:

  migration:
    container_name: migration_container
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_ADDR: ${POSTGRES_ADDR:-primary}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGSSLMODE: disable
    volumes:
      - ./migrations:/migrations
    depends_on:
      primary:
        condition: service_healthy
    networks:
      - postgres_network
    restart: on-failure:10
