# This file is used for local development purposes only
# and is ignored in cloud environments - see Dockerfile

version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ${PWD}/services/backend/deployment/postgres/migrations/volumes_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  migration:
    container_name: migration_container
    image: migration
    depends_on:
      - postgres
    build:
      dockerfile: services/backend/deployment/postgres/Dockerfile
      context: ../../../../
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_ADDR: ${POSTGRES_ADDR:-postgres:5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGSSLMODE: disable
    volumes:
      - migration:/root/.migration
    networks:
      - postgres
    restart: on-failure:10

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  migration: